export const predefinedOptions = {
  basic: {
    categories: [
      'Inbound Sales',
      'Outbound Sales',
      'Customer Service',
      'Technical Support',
      'Account Management',
      'Lead Generation',
      'Market Research',
      'Appointment Setting',
      'Order Processing',
      'Customer Retention',
      'Billing Support',
      'Product Support',
      'Help Desk',
      'Chat Support',
      'Email Support',
      'Social Media Support',
      'Survey Calls',
      'Welcome Calls',
      'Follow-up Calls',
      'Complaint Resolution',
      'Warranty Support',
      'Collections',
      'Dispatch Services',
      'Emergency Support',
      'Multilingual Support'
    ],
    seniorityLevels: [
      'Entry Level',
      'Junior',
      'Mid-Level',
      'Senior',
      'Team Lead',
      'Supervisor',
      'Manager',
      'Director'
    ],
    timeZones: [
      'New York (EST/EDT)',
      'Chicago (CST/CDT)',
      'Denver (MST/MDT)',
      'Los Angeles (PST/PDT)',
      'London (GMT/BST)',
      'Paris (CET/CEST)',
      'Dubai (GST)',
      'Singapore (SGT)',
      'Tokyo (JST)',
      'Sydney (AEST/AEDT)'
    ],
    scheduleFlexibility: [
      'Remote Work Available',
      'Flexible Hours',
      'Weekend Rotation',
      'Night Shift Available',
      'Split Shifts',
      'Part-Time Options',
      'Compressed Work Week',
      'Shift Swapping Allowed'
    ],
    destinationZones: [
      'Europe',
      'Amérique du Nord',
      'Amérique du Sud',
      'Asie',
      'Afrique',
      'Océanie',
      'Moyen-Orient'
    ]
  },
  commission: {
    currencies: [
      { code: 'USD', symbol: '$', name: 'US Dollar' },
      { code: 'EUR', symbol: '€', name: 'Euro' },
      { code: 'GBP', symbol: '£', name: 'British Pound' },
      { code: 'AUD', symbol: 'A$', name: 'Australian Dollar' },
      { code: 'CAD', symbol: 'C$', name: 'Canadian Dollar' },
      { code: 'SGD', symbol: 'S$', name: 'Singapore Dollar' },
      { code: 'HKD', symbol: 'HK$', name: 'Hong Kong Dollar' },
      { code: 'JPY', symbol: '¥', name: 'Japanese Yen' },
      { code: 'INR', symbol: '₹', name: 'Indian Rupee' },
      { code: 'AED', symbol: 'د.إ', name: 'UAE Dirham' }
    ],
    baseTypes: [
      'Fixed Salary',
      'Base + Commission',
      'Pure Commission',
      'Tiered Commission',
      'Graduated Commission'
    ],
    bonusTypes: [
      'Performance Bonus',
      'Quarterly Bonus',
      'Annual Bonus',
      'Team Bonus',
      'Signing Bonus',
      'Retention Bonus',
      'Holiday Bonus'
    ]
  },
  leads: {
    sources: [
      'Website Inquiries',
      'Social Media',
      'Email Campaigns',
      'Trade Shows',
      'Referrals',
      'Cold Calling',
      'Partner Network',
      'Online Advertising',
      'Content Marketing',
      'Direct Mail',
      'Industry Events',
      'Customer Recommendations',
      'LinkedIn Outreach',
      'Webinars',
      'Free Trials'
    ]
  },
  team: {
    roles: [
      { id: 'agent', name: 'Sales Agent', description: 'Handles direct sales and customer interactions' },
      { id: 'lead', name: 'Team Lead', description: 'Supervises and coaches a team of agents' },
      { id: 'supervisor', name: 'Supervisor', description: 'Oversees multiple teams and operations' },
      { id: 'manager', name: 'Manager', description: 'Manages department strategy and performance' },
      { id: 'trainer', name: 'Training Specialist', description: 'Conducts training and development programs' },
      { id: 'qa', name: 'Quality Analyst', description: 'Monitors and evaluates call quality' },
      { id: 'support', name: 'Support Specialist', description: 'Provides technical and process support' },
      { id: 'coordinator', name: 'Team Coordinator', description: 'Handles scheduling and administrative tasks' },
      { id: 'coach', name: 'Performance Coach', description: 'Provides one-on-one coaching and development' },
      { id: 'specialist', name: 'Product Specialist', description: 'Subject matter expert for complex inquiries' }
    ],
    territories: [
      'Afghanistan',
      'Albanie',
      'Algérie',
      'Andorre',
      'Angola',
      'Antigua-et-Barbuda',
      'Argentine',
      'Arménie',
      'Australie',
      'Autriche',
      'Azerbaïdjan',
      'Bahamas',
      'Bahreïn',
      'Bangladesh',
      'Barbade',
      'Belgique',
      'Belize',
      'Bénin',
      'Bhoutan',
      'Biélorussie',
      'Birmanie',
      'Bolivie',
      'Bosnie-Herzégovine',
      'Botswana',
      'Brésil',
      'Brunei',
      'Bulgarie',
      'Burkina Faso',
      'Burundi',
      'Cambodge',
      'Cameroun',
      'Canada',
      'Cap-Vert',
      'Centrafrique',
      'Chili',
      'Chine',
      'Chypre',
      'Colombie',
      'Comores',
      'Congo',
      'Corée du Nord',
      'Corée du Sud',
      'Costa Rica',
      'Côte d\'Ivoire',
      'Croatie',
      'Cuba',
      'Danemark',
      'Djibouti',
      'Dominique',
      'Égypte',
      'Émirats arabes unis',
      'Équateur',
      'Érythrée',
      'Espagne',
      'Estonie',
      'États-Unis',
      'Éthiopie',
      'Fidji',
      'Finlande',
      'France',
      'Gabon',
      'Gambie',
      'Géorgie',
      'Ghana',
      'Grèce',
      'Grenade',
      'Guatemala',
      'Guinée',
      'Guinée-Bissau',
      'Guinée équatoriale',
      'Guyana',
      'Haïti',
      'Honduras',
      'Hongrie',
      'Îles Cook',
      'Îles Marshall',
      'Îles Salomon',
      'Inde',
      'Indonésie',
      'Irak',
      'Iran',
      'Irlande',
      'Islande',
      'Israël',
      'Italie',
      'Jamaïque',
      'Japon',
      'Jordanie',
      'Kazakhstan',
      'Kenya',
      'Kirghizistan',
      'Kiribati',
      'Koweït',
      'Laos',
      'Lesotho',
      'Lettonie',
      'Liban',
      'Liberia',
      'Libye',
      'Liechtenstein',
      'Lituanie',
      'Luxembourg',
      'Macédoine du Nord',
      'Madagascar',
      'Malaisie',
      'Malawi',
      'Maldives',
      'Mali',
      'Malte',
      'Maroc',
      'Maurice',
      'Mauritanie',
      'Mexique',
      'Micronésie',
      'Moldavie',
      'Monaco',
      'Mongolie',
      'Monténégro',
      'Mozambique',
      'Namibie',
      'Nauru',
      'Népal',
      'Nicaragua',
      'Niger',
      'Nigeria',
      'Niue',
      'Norvège',
      'Nouvelle-Zélande',
      'Oman',
      'Ouganda',
      'Ouzbékistan',
      'Pakistan',
      'Palaos',
      'Panama',
      'Papouasie-Nouvelle-Guinée',
      'Paraguay',
      'Pays-Bas',
      'Pérou',
      'Philippines',
      'Pologne',
      'Portugal',
      'Qatar',
      'République centrafricaine',
      'République démocratique du Congo',
      'République dominicaine',
      'République tchèque',
      'Roumanie',
      'Royaume-Uni',
      'Russie',
      'Rwanda',
      'Saint-Christophe-et-Niévès',
      'Saint-Marin',
      'Saint-Vincent-et-les-Grenadines',
      'Sainte-Lucie',
      'Salvador',
      'Samoa',
      'Sao Tomé-et-Principe',
      'Sénégal',
      'Serbie',
      'Seychelles',
      'Sierra Leone',
      'Singapour',
      'Slovaquie',
      'Slovénie',
      'Somalie',
      'Soudan',
      'Soudan du Sud',
      'Sri Lanka',
      'Suède',
      'Suisse',
      'Suriname',
      'Syrie',
      'Tadjikistan',
      'Tanzanie',
      'Tchad',
      'Thaïlande',
      'Timor oriental',
      'Togo',
      'Tonga',
      'Trinité-et-Tobago',
      'Tunisie',
      'Turkménistan',
      'Turquie',
      'Tuvalu',
      'Ukraine',
      'Uruguay',
      'Vanuatu',
      'Vatican',
      'Venezuela',
      'Viêt Nam',
      'Yémen',
      'Zambie',
      'Zimbabwe'
    ]
  },
  skills: {
    languages: [
      { name: 'English' },
      { name: 'Spanish' },
      { name: 'French' },
      { name: 'German' },
      { name: 'Chinese' },
      { name: 'Japanese' },
      { name: 'Arabic' },
      { name: 'Portuguese' },
      { name: 'Russian' }
    ],
    professional: [
      'Gestion de projet',
      'Architecture logicielle',
      'Méthodologies Agile',
      'Gestion d\'équipe',
      'Planification stratégique',
      'Analyse de marché',
      'Développement commercial',
      'Gestion de la qualité',
      'Gestion des risques',
      'Conformité réglementaire'
    ],
    technical: [
      'JavaScript',
      'TypeScript',
      'Node.js',
      'React',
      'Angular',
      'Vue.js',
      'Python',
      'Java',
      'C#',
      'PHP',
      'MongoDB',
      'PostgreSQL',
      'MySQL',
      'Docker',
      'Kubernetes',
      'AWS',
      'Azure',
      'Git',
      'CI/CD',
      'REST API',
      'GraphQL',
      'Microservices',
      'DevOps'
    ],
    soft: [
      'Communication',
      'Travail d\'équipe',
      'Résolution de problèmes',
      'Adaptabilité',
      'Leadership',
      'Gestion du temps',
      'Pensée critique',
      'Créativité',
      'Empathie',
      'Gestion du stress'
    ],
    skillLevels: [
      'Basic',
      'Conversational',
      'Professional',
      'Native/Bilingual'
    ]
  },
  metrics: {
    kpis: [
      'Average Handle Time (AHT)',
      'First Call Resolution (FCR)',
      'Customer Satisfaction (CSAT)',
      'Net Promoter Score (NPS)',
      'Quality Score'
    ]
  }
};

export const sectionGuidance = {
  basic: {
    title: 'Basic Information',
    steps: [
      'Enter a clear and descriptive title for the role',
      'Select the appropriate category',
      'Choose the seniority level',
      'Specify required years of experience'
    ],
    tips: [
      'Use industry-standard job titles for better visibility',
      'Be specific about the role category to attract the right candidates',
      'Match seniority level with experience requirements',
      'Consider both minimum and preferred experience levels'
    ]
  },
  schedule: {
    title: 'Schedule & Availability',
    steps: [
      'Select working days',
      'Define working hours',
      'Specify time zones',
      'Set minimum hour requirements',
      'Choose flexibility options'
    ],
    tips: [
      'Consider multiple time zones for global coverage',
      'Be clear about shift patterns and rotations',
      'Include any flexibility in scheduling',
      'Specify both core hours and flexible time slots'
    ]
  },
  commission: {
    title: 'Commission Structure',
    steps: [
      'Select the currency',
      'Choose the commission type',
      'Set base amounts',
      'Define bonus structure',
      'Add detailed commission terms'
    ],
    tips: [
      'Be transparent about commission calculations',
      'Include all potential bonus opportunities',
      'Clearly explain performance targets',
      'Specify payment frequency and terms'
    ]
  },
  leads: {
    title: 'Lead Distribution',
    steps: [
      'Define lead types and percentages',
      'Describe each lead category',
      'List lead sources',
      'Set distribution rules'
    ],
    tips: [
      'Balance the mix of hot, warm, and cold leads',
      'Be specific about lead quality criteria',
      'Explain the lead assignment process',
      'Include information about lead follow-up expectations'
    ]
  },
  skills: {
    title: 'Required Skills',
    steps: [
      'Select required languages',
      'Choose technical skills',
      'Add soft skills',
      'Specify required tools'
    ],
    tips: [
      'Prioritize must-have vs. nice-to-have skills',
      'Be specific about language proficiency levels',
      'Include both technical and soft skills',
      'List relevant tools and software'
    ]
  },
  team: {
    title: 'Team Structure',
    steps: [
      'Define team size',
      'List team roles',
      'Select target countries',
      'Set reporting relationships'
    ],
    tips: [
      'Be clear about team hierarchy',
      'Include cross-functional relationships',
      'Specify country coverage requirements',
      'Define collaboration requirements'
    ]
  },
  docs: {
    title: 'Documentation',
    steps: [
      'List product documentation',
      'Add process guides',
      'Include training materials',
      'Specify access requirements'
    ],
    tips: [
      'Ensure all necessary resources are listed',
      'Include both internal and external documentation',
      'Specify any required certifications',
      'Note documentation update frequency'
    ]
  }
};